# Generated by Django 2.0.7 on 2018-12-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20180724_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='fav_id',
            field=models.IntegerField(default=0, verbose_name='用户ID'),
        ),
    ]
