# Generated by Django 2.0.7 on 2018-07-22 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseresource',
            old_name='addtime',
            new_name='add_time',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='addtime',
            new_name='add_time',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='addtime',
            new_name='add_time',
        ),
    ]
