# Generated by Django 2.0.7 on 2018-10-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='known',
            field=models.CharField(default='study hard', max_length=300, verbose_name='老师告诉你'),
        ),
        migrations.AddField(
            model_name='course',
            name='notes',
            field=models.CharField(default='study hard', max_length=300, verbose_name='课程须知'),
        ),
    ]
